name: NEPSE IPO Alert Cron


  workflow_dispatch:        # allows manual run too

jobs:
  trigger-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Ping IPO Script
        run: |
          echo "📡 Triggering NEPSE IPO Alert script..."
          curl -v -A "Mozilla/5.0" --retry 3 --max-time 20 https://ipoalert.42web.io/check-ipo.php?cron=1
